spring.application.name=books-management-system
server.port=8091

logging.level.org.springframework.ws=DEBUG
logging.level.org.springframework.xml=DEBUG

logging.level.org.springframework.ws.server.MessageTracing=TRACE
logging.level.org.springframework.ws.client.MessageTracing=TRACE
logging.level.org.springframework.ws.soap=TRACE
